#!/bin/bash
for G in 0 1 2 3 4 5 6 7 8 9 19 29 39 49 59 69 79 89 99; do
    for E in 1a 1b 2 3; do
        N=1;
        for O in `ls raw/giurfa-innate-expt-$E-*-log.txt`; do 
            gawk -F',' -vG=$G '($1=="m" && $2==G) {print $4 "," $7}' $O > counts-giurfa-innate-expt-$E-gen$G-seed$N.csv;
            N=$(( N+1 ));
        done;
    done;
done
