#!/bin/bash
for S in uniq multi; do
    for E in 1b 2; do
        for X in 240x240 300x300; do
            cd $S/expt-$E/$X
#            mkdir raw
#            mv giurfa* raw/
            mkdir counts-fredid
            for G in 0 1 2 3 4 5 6 7 8 9 19 29 39 49 59 69 79 89 99 124 149 174 199; do
                N=1
                for O in `ls raw/*-log.txt`; do 
                    gawk -F',' -vG=$G '($1=="n" && $2==G) {print $9 "," $7}' $O > counts-fredid/counts-giurfa-sample1x-$S-expt-$E-$X-gen$G-seed$N.csv
                    N=$(( N+1 ))
                done
            done
            cd ../../..
        done
    done
done
