#!/bin/bash

for G in 0 1 2 3 4 5 6 7 8 9 19 29 39 49 59 69 79 89 99 124 149 174 199; do
    for E in 1a 1b 2; do
        N=1;
        for O in `ls expt-$E/giurfa-*-expt-$E-*-log.txt`; do 
            gawk -F',' '{system("bash gen-mp-counts "$1" "$2);}' counts-fredid-giurfa-sample1-uniq-expt-$E-gen$G-seed$N.csv | sort > tmp1.out
            for F in `cut -d',' -f1 tmp1.out | uniq`; do
                echo -n $F","; grep $F"," tmp1.out | gawk -F',' '{C+=$2} END {print C}';
            done > counts-mps-giurfa-sample1-uniq-expt-$E-gen$G-seed$N.csv
            rm -f tmp1.out
            N=$(( N+1 ))            
        done
    done
done
