#!/bin/bash
for G in 0 1 2 3 4 5 6 7 8 9 19 29 39 49 59 69 79 89 99 124 149 174 199; do
    for E in 1a 1b 2; do
        N=1;
        for O in `ls expt-$E/giurfa-*-expt-$E-*-log.txt`; do 
            gawk -F',' -vG=$G '($1=="n" && $2==G) {print $10 "," $7}' $O > counts-fredid-giurfa-sample1-uniq-expt-$E-gen$G-seed$N.csv;
            N=$(( N+1 ));
        done;
    done;
done
