#!/bin/bash

for G in `seq 1 9`; do for L in 1 3; do for S in 1 2; do P="^F,$G,[0-9]+,$S,.*,$L$"; echo -n "$G,$S," >> counts-$L.txt; egrep $P waser-expt-5-1x2-2017-07-26-11-03-28-log.txt | wc -l >> counts-$L.txt; done; done; done

gawk -F',' '/^[0-9]+,1/ {if ($1>1) {print $1", "$3}}' counts-1.txt > l1-s1.dat
gawk -F',' '/^[0-9]+,2/ {if ($1>1) {print $1", "$3}}' counts-1.txt > l1-s2.dat
gawk -F',' '/^[0-9]+,1/ {if ($1>1) {print $1", "$3}}' counts-3.txt > l3-s1.dat
gawk -F',' '/^[0-9]+,2/ {if ($1>1) {print $1", "$3}}' counts-3.txt > l3-s2.dat

gnuplot -e "set term png; set output 'l1-s1s2.png'; set yrange [-100:2100]; set ylabel 'Number of plants'; set xlabel 'Generation'; plot 'l1-s1.dat' with lines title 'Species 1', 'l1-s2.dat' with lines title 'Species 2'"

gnuplot -e "set term png; set output 'l3-s1s2.png'; set yrange [-100:2100]; set ylabel 'Number of plants'; set xlabel 'Generation'; plot 'l3-s1.dat' with lines title 'Species 1', 'l3-s2.dat' with lines title 'Species 2'"
