#!/bin/bash
#
# Quick script to process output file of an evobee run involving
# two plant species, and produce graphs of the number of each
# species over time.
#
# Usage:
#   processDataFiles outputlogfile
#
# Author: Tim Taylor
# Last updated: 19 July 2017

if [ "$#" -ne "1" ]; then
    echo "usage: processDataFiles outputlogfile"
    exit
fi

gawk -F',' '/Species1/ {if ($2>1) {print $2", "$5}}' $1 > $1-s1.dat
gawk -F',' '/Species2/ {if ($2>1) {print $2", "$5}}' $1 > $1-s2.dat

gnuplot -e "set term png; set output '"$1"-s1s2.png'; set yrange [-50:2050]; set ylabel 'Number of plants'; set xlabel 'Generation'; plot '"$1"-s1.dat' with lines title 'Species 1', '"$1"-s2.dat' with lines title 'Species 2'"
