#!/bin/bash
for E in 1a 1b 2; do
    for G in 0 1 2 3 4 5 6 7 8 9 19 29 39 49 59 69 79 89 99; do
        for S in `seq 1 100`; do 
            gnuplot -e "filebase='counts-giurfa-arb-dom-lambda-sample1-multi-expt-"$E"-gen"$G"-seed"$S"'" plot-lambda-plain.gnuplot
        done
    done
done
