#!/bin/bash
for E in 1a 1b 2; do
    F=""
    for G in 0 1 2 3 4 5 6 7 8 9 19 29 39 49 59 69 79 89 99; do
        gawk -vG="$G" -vE="$E" '{sub(/XXX/,G,$0); sub(/NNN/,E,$0); print;}' plainplot-display-template.tex > plainplot-display-$E-$G.tex
        pdflatex plainplot-display-$E-$G.tex
        X=plainplot-display-$E-$G.pdf
        F="$F $X"  
    done
    pdfunite $F plainplot-display-combined-expt-$E.pdf
    rm -f plainplot-display-$E-*.aux
    rm -f plainplot-display-$E-*.log
    rm -f plainplot-display-$E-*.tex
    rm -f plainplot-display-$E-*.pdf    
done
